# Numpy::

* NumPy stands for Numerical Python.


* NumPy is a Python library used for working with arrays.

# Why Use NumPy?::

* In Python we have lists that serve the purpose of arrays, but they are slow to process.


* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.


* The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

# Why is NumPy Faster Than Lists?::

* NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.


* This is the main reason why NumPy is faster than lists. 

In [52]:
import numpy as np
import array

In [53]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [54]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [55]:
# Here all the elements are integers
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [56]:
# Here five elements are integers and only two float values
np.array([1,2,3,4,5,6.5,7.6])

array([1. , 2. , 3. , 4. , 5. , 6.5, 7.6])

### Observe the difference:: Here by introducing float values ,the entrie dataset is converted into floating values

### Here it is trying to typecaste the data into higher order......In the above example the higher order is float comparing to the integer

##  what does higher order mean :: 

* The biggest data element in the dataset



* Few examples: Float value is bigger than(Occupies more memory space) integer values, String values are bigger than float and integer values




# NOTE::AUTOMATIC TYPECASTING IS ONE SPECIALITY IN NUMPY::

In [6]:
# Here the higher order is string so,gradually all the elements in the dataset will get converted into string values
np.array([1,2,3,4,5,6.5,7.6,'NITISH'])

array(['1', '2', '3', '4', '5', '6.5', '7.6', 'NITISH'], dtype='<U32')

In [7]:
np.array([1.5,2.3,3.6,4.9,5.5,6.5,7.6,'NITISH',50])

array(['1.5', '2.3', '3.6', '4.9', '5.5', '6.5', '7.6', 'NITISH', '50'],
      dtype='<U32')

### Create a 1-D array containing the values 1,2,3,4,5:

In [8]:
a=np.array([1,2,3,4,5])

In [9]:
a

array([1, 2, 3, 4, 5])

## How to check dimension of array::

* NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [10]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [11]:
a.ndim

1

### Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

In [12]:
b=np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b.ndim

2

In [58]:
c=np.array([[[1, 2, 3], [4, 5, 6]]])

In [59]:
c.ndim

3

# Note: :

In [15]:
np.array([[1, 2, 3], [4, 5, 6,7]])
# Here we tried to create a 2-dimensional array but the size of elements are not same...
# so it will return an array with list of elements

C:\Users\NITHISH\AppData\Local\Temp/ipykernel_4688/384250106.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[1, 2, 3], [4, 5, 6,7]])


array([list([1, 2, 3]), list([4, 5, 6, 7])], dtype=object)

# Creating 3-d array::

* An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [16]:
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
d.ndim

3

# Higher Dimensional Arrays:

* An array can have any number of dimensions.

* When the array is created, you can define the number of dimensions by using the ndmin argument.

In [18]:
h=np.array([1, 2, 3, 4], ndmin=3)
h

array([[[1, 2, 3, 4]]])

# Important:

* In numpy ,we can create array using list and tuple



* Both will create same output

In [19]:
# Creating array using list
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [20]:
# Creating array using tuple
b=np.array((1,2,3,4))
b

array([1, 2, 3, 4])

### Access Array Elements:

* Array indexing is the same as accessing an array element.

* You can access an array element by referring to its index number.

* The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [21]:
# Get the first element from the following array:
a=np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [22]:
a[0]

1

In [23]:
a[1]

2

In [24]:
a[2]

3

### Access 2-D Arrays::



In [60]:
a=np.array([[1,2,3,4,5], [6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [61]:
a[1][4]

10

In [26]:
a[0][4]# First row and accessing the last f`ifth element

5

In [27]:
# Access 4th element in second row
a[1][3]

9

In [28]:
arr=np.array([[1,2],[5,6]])

In [29]:
arr

array([[1, 2],
       [5, 6]])

In [30]:
arr.ndim

2

In [31]:
# Matrix is also an array
np.mat(arr)

matrix([[1, 2],
        [5, 6]])

# How to convert list into array:

* There are three ways: 1.array 2.asarray 3.asanyarray

In [32]:
l=[1,2,78,79,87,45]

In [33]:
np.array(l)

array([ 1,  2, 78, 79, 87, 45])

In [34]:
np.asarray(l)

array([ 1,  2, 78, 79, 87, 45])

In [35]:
np.asanyarray(l)

array([ 1,  2, 78, 79, 87, 45])

# NumPy Array Slicing::

*  Slicing in python means taking elements from one given index to another given index.

* We pass slice instead of index like this: [start:end].

* We can also define the step, like this: [start:end:step].

* If we don't pass start its considered 0

* If we don't pass end its considered length of array in that dimension

* If we don't pass step its considered 1

### 

In [36]:
# Slice elements from index 1 to index 5 from the following array
a=np.array([1, 2, 3, 4, 5, 6, 7])
a


array([1, 2, 3, 4, 5, 6, 7])

In [37]:
a[0:]

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
a[0:7:2]

array([1, 3, 5, 7])

In [39]:
# Slice elements from index 4 to the end of the array:
a[3:]

array([4, 5, 6, 7])

In [40]:
# Slice elements from the beginning to index 4 (not included):
a[:4]

array([1, 2, 3, 4])

## Slicing 2-D Arrays:

In [41]:
# From the second element, slice elements from index 1 to index 4
a=np.array([[1,2,3,4],[5,6,7,8]])
a.ndim

2

In [42]:
a[1][1:]

array([6, 7, 8])

### ***********From both elements, return index 2:********** VERY IMP

In [43]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(a[0:2, 2])

[3 8]


In [44]:
# From both elements, slice index 1 to index 4 
# this will return a 2-D array:
a[0:2 ,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

## Checking the Data Type of an Array::

* The NumPy array object has a property called dtype that returns the data type of the array:

In [62]:
a=2

In [63]:
type(a)

int

In [45]:
a = np.array([1, 2, 3, 4])

print(a.dtype)

int32


In [46]:
# Get the data type of an array containing strings:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)


<U6


# NumPy Array Copy vs View
* The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

* The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

* The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [47]:
# Make a copy, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


### The copy SHOULD NOT be affected by the changes made to the original array.

In [48]:
# Make a view, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


### The view SHOULD be affected by the changes made to the original array.

In [49]:
# Make Changes in the VIEW:
# Make a view, change the view, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


### The original array SHOULD be affected by the changes made to the view.


## Shape of an Array::

* The shape of an array is the number of elements in each dimension.

In [50]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


### The example above returns (2, 4), which means that the array has 2 dimensions,and 4 elements each

In [51]:
arr = np.array([[1, 2, 3], [5, 6, 7]])

print(arr.shape)

(2, 3)


# Reshaping arrays